home:
    path: /
    controller: App\Controller\DefaultController::index

about:
    path: /about
    controller: App\Controller\DefaultController::about
    
careers:
    path: /careers
    controller: App\Controller\DefaultController::careers
    
contact:
    path: /contact
    controller: App\Controller\DefaultController::contact
    
detail:
    path: /books/{bookid}.html
    controller: App\Controller\BookController::detail
    
list:
    path: /book/{type}/{key}/{page}
    controller: App\Controller\BookController::list
    defaults: 
        page: 1
    requirements: 
        page: '\d+'
        
read: 
    path: /reading/{page}
    controller: App\Controller\ReadController:search
    defaults:
        page: 1
    requirements: 
        page: '\d+'

search: 
    path: /book/search
    controller: App\Controller\BookController::search
    methods: POST
    
add_tag:
    path: /book/addtag
    controller: App\Controller\BookController::addTag
    methods: GET
    
lakers: 
    path: /lakers
    controller: App\Controller\MiscController::lakers
    
wpme:
    path: /wpme/{word}
    controller: App\Controller\MiscController::wpme_detail
    
book_today_detail:
    path: /book/today
    controller: App\Controller\BookController::today_detail
    
admin:
    path: /admin
    controller: App\Controller\AdminController::admin