home:
    path: /
    controller: App\Controller\DefaultController::index

about:
    path: /about
    controller: App\Controller\DefaultController::about
    
careers:
    path: /careers
    controller: App\Controller\DefaultController::careers